export const BRANDS = [
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Skoda", label: "Skoda" },
  { value: "Ford", label: "Ford" },
  { value: "Opel", label: "Opel" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Citroen", label: "Citroen" },
  { value: "Renault", label: "Renault" },
  { value: "Toyota", label: "Toyota" },
  { value: "Honda", label: "Honda" },
  { value: "Nissan", label: "Nissan" },
  { value: "Mazda", label: "Mazda" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Lexus", label: "Lexus" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Acura", label: "Acura" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Kia", label: "Kia" },
  { value: "Genesis", label: "Genesis" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Jeep", label: "Jeep" },
  { value: "Dodge", label: "Dodge" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Tesla", label: "Tesla" },
  { value: "Volvo", label: "Volvo" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Porsche", label: "Porsche" },
  { value: "Mini", label: "Mini" },
  { value: "Fiat", label: "Fiat" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Lada", label: "Lada" },
  { value: "Geely", label: "Geely" },
  { value: "Chery", label: "Chery" },
  { value: "Haval", label: "Haval" },
  { value: "Great Wall", label: "Great Wall" },
  { value: "BYD", label: "BYD" },
]; 